# This is a basic workflow to help you get started with Actions

name: Basic Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: self-hosted
    #runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodbye World"
      - name: Delete Directory
        shell: powershell
        run: rm -r D:\temp\Siml
      - name: Make Directory
        run: mkdir D:\temp\siml
      - name: Make FIle
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: dist
          isAbsolutePath: false
          file: HelloNewWorld.txt
          content: Hello World
       
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-files
          path: dist

  job2:
    needs: job1
    runs-on: self-hosted
    steps:
      - name: Dump workflow
        run: echo "${{ github.workflow }}"   
      - name: Dump run_id
        run: echo "${{ github.run_id }}"     
      - name: Dump run_number
        run: echo "${{ github.run_number }}"
    
