# This is a basic workflow to help you get started with Actions

name: Basic Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Get Code
        uses: actions/checkout@v4
      - name: Print Goodbye
        run: echo "Goodbye World"
  job2:
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Print Hello
        run: echo "Hello Tucson"       
