# This is a basic workflow to help you get started with Actions

name: Basic Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: self-hosted
    #runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodbye World"
      #- name: Delete Directory
      #  shell: powershell
      #  run: rm -r D:\temp\siml
      #- name: Make Directory
      #  shell: powershell
      #  run: md D:\temp\siml
      - name: Make File 1
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: dist\src
          isAbsolutePath: false
          file: HelloWorld.txt
          content: Hello World
      - name: Make File 2
        uses: 1arp/create-a-file-action@0.4.5
        with:
          path: dist\src
          isAbsolutePath: false
          file: HelloTucson.txt
          content: Hello Tucson
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-files
          path: dist\src
      #- name: Download artifacts
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: my-files
      #    path: D:\temp\siml

  job2:
    needs: job1
    runs-on: self-hosted
    steps:
      - name: Dump workflow
        run: echo "${{ github.workflow }}"   
      - name: Dump run_id
        run: echo "${{ github.run_id }}"     
      - name: Dump run_number
        run: echo "${{ github.run_number }}"
    
