# This is a basic workflow to help you get started with Actions

name: Basic Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodbye World"
  job2:
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Dump workflow
        run: echo "${{ github.workflow }}"   
      - name: Dump run_id
        run: echo "${{ github.run_id }}"     
      - name: Dump run_number
        run: echo "${{ github.run_number }}"   