# This is a basic workflow to help you get started with Actions

name: Basic Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo " Goodbye World"
  job2:
    runs-on: windows-latest
    steps:
      - name: Print Job2 Action
        run: echo "Hello Tucson,AZ"
