# This is a basic workflow to help you get started with Actions

name: Basic Workflow
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodbye Terrible World"
  job2:
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Print Hello
        run: echo "Hello Tucson"       
