name: Test Workflow
on:
  - workflow_dispatch
  #- push
env:
  TARGET_DIRECTORY: 'D:\temp\siml'
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Print Greeting
        run: |
            echo $env:TARGET_DIRECTORY
            echo "Hello World"
            
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      - name: Changed Files
        uses: dorny/paths-filter@v3
        id: changes
        with:
            filters: |
                src:
                - 'src/**'
      - if: steps.changes.outputs.src == 'true'
        run: echo "Hit"
         

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files 
        env:
         ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: echo $env:ALL_CHANGED_FILES

      - name: Loop Files
        shell: bash
        run: for file in ( HW.txt HW1.txt HW2.xml HW3.log ); do echo "$file was changed"; done

          #for file in ${ALL_CHANGED_FILES}; do
          # echo "$file was changed"
          #done
            
            
      #  
      #  run: for file in ${ALL_CHANGED_FILES} do echo "$file was changed"
      #  run: for %f in ( ${{ ALL_CHANGED_FILES }} ) do echo "$file was changed"
      #  for %f in (*.doc *.txt) do type %f 

      - name: Print Goodbye
        run: echo "Goodbye World"
      #- name: Git Version
      #  run: |
      #      cd "C:\Program Files\Git\cmd"
      #      dir
      #      git version
     


