name: Test Workflow
on:
  - workflow_dispatch
  #- push
env:
  TARGET_DIRECTORY: 'D:\temp\siml'
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      #- name: Changed Files
      #  uses: dorny/paths-filter@v3
      #  id: changes
      #  with:
      #      filters: |
      #          src:
      #          - 'src/**'
      #      token: ${{ secrets.MYTOKEN }}   
      #- name: Print Goodbye
      #  run: echo "Goodbye World"
      - name: Git Version
        run: |
            cd "C:\Program Files\Git\cmd"
            dir
     


