name: Test Workflow
on:
  - workflow_dispatch
  #- push
env:
  TARGET_DIRECTORY: 'D:\temp\siml'
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Print Greeting
        run: |
            echo $env:TARGET_DIRECTORY
            echo "Hello World"
            
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

      
      - name: Changed Files
        uses: dorny/paths-filter@v3
        id: changes
        with:
            filters: |
                src:
                - 'src/**'
      - if: steps.changes.outputs.src == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changes.outputs.scr_files }}
        run: echo $env:ALL_CHANGED_FILES

      #- name: Get changed files
      #  id: changed-files
      #  uses: tj-actions/changed-files@v44

      #- name: List all changed files 
      #  env:
      #   ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #  run: echo $env:ALL_CHANGED_FILES

      #- name: Loop Files
      #  env:
      #   ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #  shell: bash
      #  run: |
      #    for file in ${ALL_CHANGED_FILES}; do echo "$file"; done

      - name: Print Goodbye
        run: echo "Goodbye World"
 


