name: Test Workflow
on:
  - workflow_dispatch
  #- push
env:
  TARGET_DIRECTORY: 'D:\temp\siml'
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
            path: main
            token: ${{ secrets.MYTOKEN }}
            sparse-checkout: src
      - name: Change Files
        uses: dorny/paths-filter@v3
        id: changes
        with:
            filters: |
             src:
              - 'src/**'
    
      # run only if some file in 'src' folder was changed
      #  if: steps.changes.outputs.src == 'true'
      #  run: echo "hit"

      - name: Print Goodbye
        run: echo "Goodbye World"
     


